### ISSUE TITLE
Build time

### ISSUE THREAD

**Issue by sayrer** [google/cargo-raze#132]
In working on

https://github.com/dtolnay/cxx/pull/32

we noticed `cargo install cargo-raze` is very slow. While I think Cargo should be able to install pre-built binaries, is there some way to speed this up in the short term?

**Comment by luser** [comment]
The killer is the dependency on `cargo` itself:
https://github.com/google/cargo-raze/blob/818ca547e6febf6ea973669ae341c00986425a9a/impl/Cargo.toml#L27

It looks like `cargo-raze` is actually using cargo internals so I don't see a feasible way to replace that. If it were just the metadata there's a [`cargo-meta`](https://crates.io/crates/cargo-meta) crate that provides a nice API over the `cargo metadata` command without pulling in all of cargo itself.

When I was at Mozilla a colleague implemented [cargo's `--build-plan` support](https://doc.rust-lang.org/cargo/reference/unstable.html#build-plan) which is probably *almost* what you want here except [apparently it has a bunch of problems that need to be addressed](https://github.com/rust-lang/cargo/issues/7614) (and it might need to be redesigned for a v2). Given that you have a working tool here it'd probably be useful for you to note what the existing build plan functionality is lacking compared to the method you currently use.

**Comment by acmcarther** [comment]
Sorry for the delay https://github.com/google/cargo-raze/issues/132#issuecomment-585001351 is exactly correct. The slowness is compiling cargo.

IIRC, the dependence on cargo's internals is already replacable with a call out to `cargo metadata`. The ["MetadataFetcher" trait](https://github.com/google/cargo-raze/blob/818ca547e6febf6ea973669ae341c00986425a9a/impl/src/metadata.rs#L45-L47) was actually created with this purpose and a "CargoSubcommandMetadataFetcher" was written to be used in place of cargo internals. I think both codepaths existed at the time of writing because the cargo metadata subcommand was new... or maybe there was something missing from the generated metadata.

There's been some development since I originally started this work, but the ultimate path forward would be to drop the "CargoInternalsMetadataFetcher" and push forward with the subcommand fetcher. Any other dependencies on cargo are incidental and could be replaced by local types as has already been done with the metadata types. 

I'm a bit busy right now, but I'll take a look at this this weekend. If this issue is super stale and I've dropped the ball, ping back here again when you're feeling impatient. Alternatively, send a pull request.

**Comment by sayrer** [comment]
I worked on this a bit in #142, but it's not ready to merge.

**Comment by dfreese** [comment]
Can this be closed with #156?

**Comment by UebelAndre** [comment]
@acmcarther do you know if this was resolved?
