### ISSUE TITLE
Request: Update the examples directory

### ISSUE THREAD

**Issue by UebelAndre** [google/cargo-raze#190]
Every time `smoke-test.sh` is run, it creates huge amount of diffs in `./examples/*` would it be possible to have these examples regenerated?

**Comment by samschlegel** [comment]
It's unclear to me why this directory exists. Is it so that people can see what the generated structure looks like without having to run it themselves? I think that makes sense to have.

It might make sense to have one of the tests in TravisCI be that no changes were made in `examples` when running `smoke-test.sh`. `examples/WORKSPACE` was updated manually and not in the smoke-test, so CI might not even be testing the right WORKSPACE config. It also makes it much more noisy and painful to add new smoke tests when the repo isn't up to date.

Possibly splitting the example gen out of smoke-test.sh so that not everything has to be built in order to generate would make this easier as well.

**Comment by UebelAndre** [comment]
> It's unclear to me why this directory exists. Is it so that people can see what the generated structure looks like without having to run it themselves? I think that makes sense to have.

Isn't `./examples` the directory is? A place where people can see what the generated structure looks like?

> It might make sense to have one of the tests in TravisCI be that no changes were made in `examples` when running `smoke-test.sh`. `examples/WORKSPACE` was updated manually and not in the smoke-test, so CI isn't using the changes that were made.

I do feel like the state of `./smoke-test` and `./example` isn't that great right now and I feel like something could be done in in TravisCI to clean them up.


> Those changes were also invalid (bad sha256) so if someone tries to copy them they're going to have a bad time.

What changes? The changes in #191 ?

The entire reason I requested this update was so that when I run smoketest I don't have a huge diff but additionally, it seems a lot has changed since `./examples` was first added

**Comment by samschlegel** [comment]
Oh man I wrote up a whole response to this but it poofed 😞 Also my first response was late at night and in hindsight it reads a little loopy lol

> Isn't ./examples the directory exactly this? A place where people can see what the generated structure looks like?
Yeah it is. I think the point I was trying to make was that it isn't always kept up to date, so it doesn't feel like it does that job very well

> What changes? The changes in #191 ?
Ah no, I meant the changes that had been made to `examples/WORKSPACE` in https://github.com/google/cargo-raze/commit/e2cc36f292514918a8d17cbced1dbcccf805c68c . At least for me the SHA was wrong, so it didn't work if you just went into the examples directory and tried to build anything. It seems like it's been manually edited several times instead of reusing what the smoke test generates. I added an issue to track adding a check to CI https://github.com/google/cargo-raze/issues/198

**Comment by UebelAndre** [comment]
> Oh man I wrote up a whole response to this but it poofed 😞 

Oh no, that sucks!

> Also my first response was late at night and in hindsight it reads a little loopy lol

Haha no worries, thanks for your reply! 😄 

> I added an issue to track adding a check to CI #198

This sounds great to me. Though, that said, do you think #191 is still worth attempting to apply? Or do you think it'd be better to instead work on #198?

**Comment by samschlegel** [comment]
#191 is going to be a requirement for merging #199 since without it, the test fails 😄

**Comment by UebelAndre** [comment]
@samschlegel Ok, I updated the PR based on your feedback. Two notable changes added as well are that I renamed `WORKSPACE` to `WORKSPACE.bazel` and I added a `.bazelversion` file.

**Comment by UebelAndre** [comment]
#191 has been merged thus satisfying this request.
