### ISSUE TITLE
Support non-standard registries in remote mode

### ISSUE THREAD

**Issue by acmcarther** [google/cargo-raze#24]
Remote GenMode is currently masquerading as if it supports arbitrary registries, but in reality it only supports the standard registry due to how it is pulling down the crates:

https://github.com/google/cargo-raze/blob/726148a42640d257577bb3859bae629529d53f3b/src/templates/remote_crates.bzl.template#L11

Normally, this should be using something derived from the registry url, but there is a weird issue described in ancient times here: https://github.com/acmcarther/cargo-raze-vendor/issues/3

**Comment by acmcarther** [comment]
The url in that issue is dead (as it wasn't directly linked to the commit)

Here is the relevant snippet

```
    urls = [
      # Bazel's downloader renders HTTP page instead of downloading for some reason.
      #"https://crates.io/api/v1/crates/{crate_name}/{crate_version}/download"
      "https://crates-io.s3-us-west-1.amazonaws.com/crates/{crate_name}/{crate_name}-{crate_version}.crate",
    ]
```

**Comment by UebelAndre** [comment]
I believe this is now supported

**Comment by illicitonion** [comment]
I have a series of patches which support additional registries as per https://doc.rust-lang.org/cargo/reference/registries.html - this is not just "accept a different mirror to download crates from crates.io" but actually supporting the `registry` property on dependencies. I'm not quite sure the best way to expose this as config. Would appreciate some thoughts!

The tricky part is that whenever we invoke `cargo` for any reason (`cargo metadata` or `cargo generate-lockfile`, including the no-deps `cargo metadata` we do to detect path dependencies and workspaces before we copy files out of input tree), we need to either:
1. Have a `.cargo/config.toml` file present, with a `[registries]` section
2. Set environment variables specifying registry index URLs

These would also need to be set up if someone were to manually run `cargo` (e.g. to debug weird resolution with `cargo tree` or similar).

I think there are two reasonable interfaces we could offer to folks:

1. If there's a `.cargo/config.toml` file present in the dir containing the `Cargo.toml` we're processing, try to honour it (i.e. copy it into temporary locations we generate). We could either honour the whole thing, or parse out specifically sections we understand and ignore (or error on) anything extra.
2. Add some new config keys to `RazeSettings`, and use them to either set the env vars whenever we invoke `cargo`. We don't want to generate a synthetic `.cargo/config.toml` file because we also invoke `cargo metadata` in the input Cargo.toml's dir, and we don't want to mess with any existing files that may be in that directory.

1 has the advantage of using an existing configuration format, and making things like `cargo tree` Just Work. If users are _already_ creating `.cargo/config.toml` files so that `cargo` Just Works for them, it avoids them needing to duplicate that config.
2 has the advantage of keeping config located in one place, with the disadvantage that we need to make sure that every single `cargo` invocation needs the env vars set (and the `cargo-metadata` crate makes passing env vars slightly fiddly, but it's doable).

I'm leaning towards 1 - I feel like "use Cargo's way of doing config" sufficiently overrides the "put config in two places" concern, but would appreciate others input, or any other ideas!

Once we decide on an interface, I will send out some patches :)

/cc @UebelAndre @acmcarther @dfreese

**Comment by UebelAndre** [comment]
I think I prefer the second option. I don't feel we have an egregious amount of calls to cargo and if we did then it'd be in our best interest to write some utility to handle that. My concern with using a [config.toml](https://doc.rust-lang.org/cargo/reference/config.html) is that there are many settings that don't apply to anything `cargo-raze` is doing. But that said, I'm not actively against the first option.

**Comment by illicitonion** [comment]
See #412 - I ended up going for the first option because it turns out we need the config to be present before we parse out `RazeSettings` from the `Cargo.toml`, and side-loading the config before that seems complex.
