### ISSUE TITLE
Support vendoring directly into root (workspace_path = "//")

### ISSUE THREAD

**Issue by mfarrugi** [google/cargo-raze#42]
Offspring of https://github.com/acmcarther/cargo-raze/issues/12

This is a mild convience that would let us refer to dependent crates as something like `@cargo//:log`.

This may also help with efforts around canonical dependency naming, though I suspect we are far from having bazel+rust projects depend on each other without going through cargo.

**Comment by Zintinio** [comment]
This would also help with dev tooling. Some editors / IDEs expect the `Cargo.toml` to be located in the root directory, and break unexpectedly if this is not the case. So to keep tools working, one needs to have both valid Bazel BUILD files and valid Cargo.toml files.

**Comment by acmcarther** [comment]
Ack, will work on this tonight. 

As noted in #12, the only reason this isn't currently supported is because I was lazy when handling paths, just following a convention of retaining a trailing slash everywhere. "//" is pathological in this simplistic model (in that "///" is invalid, and "/" is also invalid).

**Comment by Zintinio** [comment]
@acmcarther thanks for the fast response! If you need help testing or any other simple tasks, please feel free to ping me.

**Comment by mfarrugi** [comment]
@Zintinio you might want to chime in on https://github.com/bazelbuild/rules_rust/issues/71 as well if your usecase isn't already covered.
