### ISSUE TITLE
Question: Why not generate BUILD.bazel like other configuration generators?

### ISSUE THREAD

**Issue by mstg** [google/cargo-raze#92]
Hello!
This may be a "corner case" situation, but given other tools like Gazelle is generating BUILD.bazel, why isn't cargo-raze doing the same?

This would especially be helpful when using a case insensitive file system (Windows + WSL) considering some crates (openssl-sys) can have a directory called `build` and that makes cargo-raze fail with the following error message:
```
error: Is a directory (os error 21)
```

One can circumvent this problem by manually changing and recompiling, but maybe it'll be better to change it all together to BUILD.bazel. Any thoughts?

**Comment by acmcarther** [comment]
Outputting `BUILD` instead of `BUILD.bazel` was not a deliberate choice on my part. The tool was developed primarily with the context of Google's internal monorepo, which still typically follows the `BUILD` convention. I'm quite open to converging on the more common filename.

I do have a concern that making this change quietly would cause subsequent runs of `cargo-raze` over existing filetrees to end up with two BUILD files, so a PR that makes this change should either make the output configurable, or be inteligent enough to remove any existing `BUILD` files. I don't have a strong opinion about those options.

My bandwidth is seriously limited recently, so I can't promise this change will happen quickly.

**Comment by mstg** [comment]
Thanks for your response.
Maybe a flag to output `BUILD.bazel` instead of `BUILD` could be introduced? Then it can just be added to the README for case insensitive file systems.

I'll take a look and see what I can do!

**Comment by mstg** [comment]
Closing this issue in favor of #93 PR
